config/routes.rb
Rails.application.routes.draw do
  resources :students, only: [:show, :new, :index, :create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'students#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort, optional: true

  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates :name, exclusion: {in: ['DROP TABLE']}

  validate :must_be_eighteen

  # 1. student email must be unique

  # 2. student must be eighteen years old
  # (date put into form - 18.years > Date.Today)

  # 3. students names cannot be 'DROP TABLE'

  def must_be_eighteen
    if dob && dob.to_date >= 18.years.ago
      self.errors.add(:dob, 'Student must be atleast 18 years old')
    end
  end

  # def not_silly_name
  #   if name == 'DROP TABLE'
  #     errors.add(:name, 'Name cannot be DROP TABLE')
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # def screenname=(screename)
  #   self.username=(screename)
  # end

  # def password=(password)
  #   encrypted_pw = Digest::SHA256.base64digest(password)
  #   self.password_digest = encrypted_pw
  # end
  #
  # def authenticate(password)
  #   self.password_digest == Digest::SHA256.base64digest(password)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def is_authenticated?
    if !current_user
      flash[:message] = 'You muts be logged in to do that'
      redirect_to login_path
    end
  end

  #memoization
  def current_user
    # if @current_user
    #   @current_user
    # else
    #   @current_user = User.find_by(id: session[:user_id])
    # end
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:user][:username])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to students_path
    else
      flash[:message] = 'User could not be found'
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :is_authenticated?, only: [:new, :create]

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new
    end

  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  </head>
  <div class="ui  teal inverted menu">
    <a href="/" class="item">
      <h1>Student Lister</h1>
    </a>
    <div class="right menu">
     <a class="item" href="<%= new_student_path %>">
       Create a New Student
     </a>
     <% if logged_in? %>
        <div class="item">Welcome <%= current_user.username %></div>
     <% end %>

     <% if logged_in? %>
        <%= link_to 'Logout', '/logout', {class: 'item', method: 'DELETE'} %>
     <% else %>
       <a class="item" href="<%= login_path %>">
         Login
       </a>
     <% end %>

   </div>
  </div>
  <body>
    <div class="ui centered grid ">
      <div class="eight wide column">

        <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/students/index.html.erb
<h1>All Students</h1>
<% if current_user %>
  <h1>Welcome <%= current_user.username %></h1>
<% end %>
<div class= 'ui huge middle aligned selection divided list'>
  <% @students.each do |student| %>
    <div class="item">
      <%= link_to student.name, student_path(student) %>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>Create a Student</h1>

<% if @student.errors.full_messages %>
  <% @student.errors.full_messages.each do |error| %>
    <p><%=error %></p>
  <% end %>
<% end %>

<% if flash[:message] %>
  <p><%=flash[:message]%></p>
<% end %>

<%= form_for @student, html: {class: 'ui form'} do |f| %>
  <div class="field">
    <%= f.text_field(:name, placeholder: 'Enter the student name...') %>
  </div>
  <div class="field">
    <%= f.text_field :email, placeholder: 'Enter the student email...' %>
  </div>
  <div class="field">
    <%= f.date_field :dob %>
  </div>
  <div class="field">
    <%= f.collection_select(:cohort_id, Cohort.all, :id, :name) %>
  </div>
  <%= f.submit({class: 'ui huge pink button'}) %>
<% end %>

app/views/students/show.html.erb
<div class='ui raised segment'>
  <div class='ui fluid card'>
    <div class='huge content'>
      <div class='header'><h1><%= @student.name %></h1></div>
      <div class="meta">
         <span class="date">
           <h3><%= @student.dob.to_date %></h3>
         </span>
      </div>
      <div class="description">
        <h3><%= @student.email %></h3>
      </div>
    </div>
  </div>
</div>